Disabled code that resets qApp.
The resetting code was first introduced by commit
80a6f91c553eaf9ed4d7d002a5abb442693e8e08 and modified by commit
5376a134f13124b9b228dd160f151a7c8eccd09a.  These changes introduced a
regression in Houdini where "QtWidgets.QApplication.instance()" returned
a QCoreApplication object instead of a QApplication object.

The regression was later fixed by commits
cfe993ac3dfdcd5f27ba34c3977500e57230c3ec and
9fe9a67a171875507231e55a512210d527cd9255 but then introduced another
regression where some PySide2 methods failed due to argument type
errors.

For example:
"""
TypeError: 'PySide2.QtGui.QSyntaxHighlighter.setDocument' called with
wrong argument types:
  PySide2.QtGui.QSyntaxHighlighter.setDocument(QTextDocument)
Supported signatures:
  PySide2.QtGui.QSyntaxHighlighter.setDocument(PySide2.QtGui.QTextDocument)
"""

Disabling the qApp resetting code introduced by the commits mentioned
above fixes both regressions in Houdini.